using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NetworkItemSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _key;

    [RealtimeProperty(2, true, true)]
    private string _spawnUrl;

    [RealtimeProperty(3, true, true)]
    private string _spawnParentKey;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class NetworkItemSyncModel : RealtimeModel {
    public string key {
        get {
            return _keyProperty.value;
        }
        set {
            if (_keyProperty.value == value) return;
            _keyProperty.value = value;
            InvalidateReliableLength();
            FireKeyDidChange(value);
        }
    }
    
    public string spawnUrl {
        get {
            return _spawnUrlProperty.value;
        }
        set {
            if (_spawnUrlProperty.value == value) return;
            _spawnUrlProperty.value = value;
            InvalidateReliableLength();
            FireSpawnUrlDidChange(value);
        }
    }
    
    public string spawnParentKey {
        get {
            return _spawnParentKeyProperty.value;
        }
        set {
            if (_spawnParentKeyProperty.value == value) return;
            _spawnParentKeyProperty.value = value;
            InvalidateReliableLength();
            FireSpawnParentKeyDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(NetworkItemSyncModel model, T value);
    public event PropertyChangedHandler<string> keyDidChange;
    public event PropertyChangedHandler<string> spawnUrlDidChange;
    public event PropertyChangedHandler<string> spawnParentKeyDidChange;
    
    public enum PropertyID : uint {
        Key = 1,
        SpawnUrl = 2,
        SpawnParentKey = 3,
    }
    
    #region Properties
    
    private ReliableProperty<string> _keyProperty;
    
    private ReliableProperty<string> _spawnUrlProperty;
    
    private ReliableProperty<string> _spawnParentKeyProperty;
    
    #endregion
    
    public NetworkItemSyncModel() : base(null) {
        _keyProperty = new ReliableProperty<string>(1, _key);
        _spawnUrlProperty = new ReliableProperty<string>(2, _spawnUrl);
        _spawnParentKeyProperty = new ReliableProperty<string>(3, _spawnParentKey);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _keyProperty.UnsubscribeCallback();
        _spawnUrlProperty.UnsubscribeCallback();
        _spawnParentKeyProperty.UnsubscribeCallback();
    }
    
    private void FireKeyDidChange(string value) {
        try {
            keyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireSpawnUrlDidChange(string value) {
        try {
            spawnUrlDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireSpawnParentKeyDidChange(string value) {
        try {
            spawnParentKeyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _keyProperty.WriteLength(context);
        length += _spawnUrlProperty.WriteLength(context);
        length += _spawnParentKeyProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _keyProperty.Write(stream, context);
        writes |= _spawnUrlProperty.Write(stream, context);
        writes |= _spawnParentKeyProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Key: {
                    changed = _keyProperty.Read(stream, context);
                    if (changed) FireKeyDidChange(key);
                    break;
                }
                case (uint) PropertyID.SpawnUrl: {
                    changed = _spawnUrlProperty.Read(stream, context);
                    if (changed) FireSpawnUrlDidChange(spawnUrl);
                    break;
                }
                case (uint) PropertyID.SpawnParentKey: {
                    changed = _spawnParentKeyProperty.Read(stream, context);
                    if (changed) FireSpawnParentKeyDidChange(spawnParentKey);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _key = key;
        _spawnUrl = spawnUrl;
        _spawnParentKey = spawnParentKey;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
