using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel(true)]
public partial class DispenserSyncModel
{
    [RealtimeProperty(3, true, true)]
    private string _key;

    [RealtimeProperty(1, false)]
    private float _scrollValue;

    [RealtimeProperty(2, true)]
    private int _counter;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class DispenserSyncModel : RealtimeModel {
    public float scrollValue {
        get {
            return _scrollValueProperty.value;
        }
        set {
            if (_scrollValueProperty.value == value) return;
            _scrollValueProperty.value = value;
            InvalidateUnreliableLength();
        }
    }
    
    public string key {
        get {
            return _keyProperty.value;
        }
        set {
            if (_keyProperty.value == value) return;
            _keyProperty.value = value;
            InvalidateReliableLength();
            FireKeyDidChange(value);
        }
    }
    
    public int counter {
        get {
            return _counterProperty.value;
        }
        set {
            if (_counterProperty.value == value) return;
            _counterProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(DispenserSyncModel model, T value);
    public event PropertyChangedHandler<string> keyDidChange;
    
    public enum PropertyID : uint {
        Key = 3,
        ScrollValue = 1,
        Counter = 2,
    }
    
    #region Properties
    
    private ReliableProperty<string> _keyProperty;
    
    private UnreliableProperty<float> _scrollValueProperty;
    
    private ReliableProperty<int> _counterProperty;
    
    #endregion
    
    public DispenserSyncModel() : base(new MetaModel()) {
        _keyProperty = new ReliableProperty<string>(3, _key);
        _scrollValueProperty = new UnreliableProperty<float>(1, _scrollValue);
        _counterProperty = new ReliableProperty<int>(2, _counter);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _keyProperty.UnsubscribeCallback();
        _counterProperty.UnsubscribeCallback();
    }
    
    private void FireKeyDidChange(string value) {
        try {
            keyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = MetaModelWriteLength(context);
        length += _keyProperty.WriteLength(context);
        length += _scrollValueProperty.WriteLength(context);
        length += _counterProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        WriteMetaModel(stream, context);
        
        var writes = false;
        writes |= _keyProperty.Write(stream, context);
        writes |= _scrollValueProperty.Write(stream, context);
        writes |= _counterProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case MetaModel.ReservedPropertyID: {
                    ReadMetaModel(stream, context);
                    break;
                }
                case (uint) PropertyID.Key: {
                    changed = _keyProperty.Read(stream, context);
                    if (changed) FireKeyDidChange(key);
                    break;
                }
                case (uint) PropertyID.ScrollValue: {
                    changed = _scrollValueProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.Counter: {
                    changed = _counterProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _key = key;
        _scrollValue = scrollValue;
        _counter = counter;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
