using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TransformSyncModel
{
    [RealtimeProperty(1, true, true)]
    private string _key;

    [RealtimeProperty(2, true, true)]
    private string _spawnItemPrefabPath;

    //[RealtimeProperty(3, true, true)]
    //private string _spawnUrl;

    //[RealtimeProperty(4, true, true)]
    //private string _spawnParentKey;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TransformSyncModel : RealtimeModel {
    public string key {
        get {
            return _keyProperty.value;
        }
        set {
            if (_keyProperty.value == value) return;
            _keyProperty.value = value;
            InvalidateReliableLength();
            FireKeyDidChange(value);
        }
    }
    
    public string spawnItemPrefabPath {
        get {
            return _spawnItemPrefabPathProperty.value;
        }
        set {
            if (_spawnItemPrefabPathProperty.value == value) return;
            _spawnItemPrefabPathProperty.value = value;
            InvalidateReliableLength();
            FireSpawnItemPrefabPathDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(TransformSyncModel model, T value);
    public event PropertyChangedHandler<string> keyDidChange;
    public event PropertyChangedHandler<string> spawnItemPrefabPathDidChange;
    
    public enum PropertyID : uint {
        Key = 1,
        SpawnItemPrefabPath = 2,
    }
    
    #region Properties
    
    private ReliableProperty<string> _keyProperty;
    
    private ReliableProperty<string> _spawnItemPrefabPathProperty;
    
    #endregion
    
    public TransformSyncModel() : base(null) {
        _keyProperty = new ReliableProperty<string>(1, _key);
        _spawnItemPrefabPathProperty = new ReliableProperty<string>(2, _spawnItemPrefabPath);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _keyProperty.UnsubscribeCallback();
        _spawnItemPrefabPathProperty.UnsubscribeCallback();
    }
    
    private void FireKeyDidChange(string value) {
        try {
            keyDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireSpawnItemPrefabPathDidChange(string value) {
        try {
            spawnItemPrefabPathDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _keyProperty.WriteLength(context);
        length += _spawnItemPrefabPathProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _keyProperty.Write(stream, context);
        writes |= _spawnItemPrefabPathProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Key: {
                    changed = _keyProperty.Read(stream, context);
                    if (changed) FireKeyDidChange(key);
                    break;
                }
                case (uint) PropertyID.SpawnItemPrefabPath: {
                    changed = _spawnItemPrefabPathProperty.Read(stream, context);
                    if (changed) FireSpawnItemPrefabPathDidChange(spawnItemPrefabPath);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _key = key;
        _spawnItemPrefabPath = spawnItemPrefabPath;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
